<!DOCTYPE html>

<html lang="Pt-BR">

    <head>

        <title>César Augusto</title>

        

        <meta charset="utf-8" />

        <meta name="viewport" content="width=device-width, user-scalable=no" >

        <link rel="shortcut icon" href="/assets/img/logo.ico" type="image/x-icon" />

        

        <?php include('includes/head.php'); ?>

        

        <script>

            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){

            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),

            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)

            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');



            ga('create', 'UA-60881501-1', 'auto');

            ga('send', 'pageview');



        </script>

        

    </head>

    <body>

    <br/>


     <a id="lnk-inicio" name="inicio"></a>

        <header>



          <input type="checkbox" id="control-nav" />

          <label for="control-nav" class="control-nav"></label>

          <label for="control-nav" class="control-nav-close"></label>



          <nav class="float-r">

            <div class="menu">

                <ul class="list-auto">

                  <li class="itens_menu">

                      <a id="mn-inicio" class="mn-item" href="#inicio" >Inicio</a>

                  </li>

                    <li class="itens_menu">

                        <a id="mn-noticias" class="mn-item" href="#noticias" >Notícias</a>

                    </li>

                  <li class="itens_menu">

                    <a id="mn-sobremim" class="mn-item" href="#sobremim" >Sobre mim</a>

                  </li>

                  <li class="itens_menu">

                    <a id="mn-curriculo" class="mn-item" href="#curriculo" >Currículo</a>

                  </li>

                  <li class="itens_menu">

                    <a id="mn-contato" class="mn-item" href="#contato"  >Contato</a>

                  </li>

                </ul>

            </div>

          </nav>

        </header>


         <?php
            foreach($view_listar_banner as $banner): ?>
                <div class="banner" style="background: url('<?php echo URL_BANNER .$banner->url; ?>') no-repeat center center; background-size: cover; overflow: auto; margin: 2.4% 0px;">

                </div>
         <?php endforeach; ?>


     <a id="lnk-noticias" name="noticias"></a>

     <div class="conteiner">

         <div class="bloco_noticias">

             <div class="noticias">

                 <center><h2 class="titulo_telas"><i>Notícias</i></h2>


                     <ul class="listar_noticias">

                         <?php
                               foreach($view_listar_noticias as $noticias):?>
                                   <a style="color: #000000;" href="noticia/ler/<?php echo $noticias->id_noticias; ?>">
                                   <li class="li_noticias" >
                                       <p style="font-size: 23px;"><b><?php echo $noticias->titulo; ?></b></p>

                                       <?php $imagem_noticia =  $view_listar_foto_noticia->listar_fotos($noticias->id_noticias);
                                         foreach($imagem_noticia as $img_noticia){

                                             if($img_noticia->principal !== '1' && $img_noticia->principal !== '0'){ ?>
                                                 <div style="background: url('/assets/img/sem_imagem.png') no-repeat center center; background-size: cover; overflow: auto; height: 70%; border: 3px solid #004560; ">

                                                 </div>
                                          <?php   }

                                             if($img_noticia->principal === '1'){ ?>
                                                 <div style="background: url('<?php echo URL_NOTICIA .$img_noticia->url; ?>') no-repeat center center; background-size: cover; overflow: auto; height: 70%; border: 3px solid #004560; ">

                                                 </div>
                                             <?php
                                             }

                                         }
                                       ?>
                                       <p style="font-size: 12px;">Data:<?php echo $noticias->data_mostrar; ?></p>
                                   </li>
                                   </a>
                         <?php endforeach; ?>

                     </ul>

                     <p ><a href="todasNoticias" class="todas_noticias_ph" >Todas as notícias.</a></p>

             </div>

         </div>

     </div>


     

        <a id="lnk-sobremim" name="sobremim"></a>

        <div class="conteiner">            

            <div class="sobre_mim">                

                <center><img src="/assets/img/quem_sou.png"/></center>

                

                <div class="descricao_sobre_mim">

                    <center><h2 class="titulo_telas"><i>Sobre mim</i></h2>

                        <?php
                           foreach( $view_listar_sobre as $sobre_nos ): ?>
                               <h2 class="texto_telas" ><?php echo $sobre_nos->descricao; ?></h2>
                        <?php endforeach;?>

                    </center>

                </div>

            </div>   

        </div>

        

        <a id="lnk-curriculo" name="curriculo"></a>

        <div class="conteiner">

            <div class="bloco_curriculo">

                <div class="curriculo">

                    <center><img src="/assets/img/curriculo.png"/></center>

                    <center><h2 class="titulo_telas"><i>Currículo</i></h2>

                </div>


                <div class="pdf_curriculo">

                    <a href="/assets/pdf/curriculo.pdf" class="link_pdf" target="_blank" ><img src="/assets/img/baixar_botao.png" /> Visualizar currículo.</a>

                </div>

            </div>

        </div>

        

        <a id="lnk-contato" name="contato"></a>

        <div class="conteiner">

            <div class="bloco_passatempo" >

                    <center><h2 class="titulo_telas_contato"><i>Contato</i></h2></center>


                    <form id="formulario" name="form" class="form" method="post" >

                        <ul class="inicio_lista_form">

                            <li class="lista_form">
                                <label class="labels">
                                    Nome
                                    <input class="inputs" type="text" id="nome" name="nome" />
                                </label>
                            </li>

                            <li class="lista_form">
                                <label class="labels">
                                    E-mail
                                    <input class="inputs" type="text" id="email" name="email" />
                                </label>
                            </li>
                        </ul>
                            <ul class="inicio_lista_form">
                                <li class="lista_form_textarea">
                                    <label class="labels">
                                        Mensagem
                                        <textarea name="texto" style=" width: 86%; height: 161px;" ></textarea>
                                    </label>
                                </li>
                            </ul>
                        <ul class="inicio_lista_form">
                            <li class="lista_form">
                                <label class="labels">
                                    <input class="botao_cadastrar" type="button" value="Enviar" onclick="enviar_contato();" />
                                </label>
                            </li>
                        </ul>

                    </form>
                <a target="_blank" href="https://github.com/ckcesar"><img src="/assets/img/git.png" /></a><br/>
                <a target="_blank" href="https://www.facebook.com/kelli.cesar"><img src="/assets/img/face.png" /></a>
            </div>



        </div>


    </body>



</html>