<!DOCTYPE html>

<html lang="Pt-BR">

    <head>

        <title>César Augusto</title>

        

        <meta charset="utf-8" />

        <meta name="viewport" content="width=device-width, user-scalable=no" >

        <link rel="shortcut icon" href="/assets/img/logo.ico" type="image/x-icon" />

        

        <?php include('includes/head.php'); ?>

        

        <script>

            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){

            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),

            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)

            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');



            ga('create', 'UA-60881501-1', 'auto');

            ga('send', 'pageview');



        </script>

        

    </head>

    <body>


        <header>



          <input type="checkbox" id="control-nav" />

          <label for="control-nav" class="control-nav"></label>

          <label for="control-nav" class="control-nav-close"></label>



          <nav class="float-r">

            <div class="menu">

                <ul class="list-auto">

                  <li class="itens_menu">

                      <a  href="home" >Inicio</a>

                  </li>

                    <li class="itens_menu">

                        <a id="mn-noticias" class="mn-item" href="#noticias" >Notícias</a>

                    </li>

                  <li class="itens_menu">

                    <a id="mn-sobremim" class="mn-item" href="#sobremim" >Sobre mim</a>

                  </li>

                  <li class="itens_menu">

                    <a id="mn-curriculo" class="mn-item" href="#curriculo" >Currículo</a>

                  </li>

                  <li class="itens_menu">

                    <a id="mn-contato" class="mn-item" href="#contato"  >Contato</a>

                  </li>

                </ul>

            </div>

          </nav>

        </header>


         <?php
            foreach($view_listar_banner as $banner): ?>
                <div class="banner" style="background: url('<?php echo URL_BANNER .$banner->url; ?>') no-repeat center center; background-size: cover; overflow: auto; margin: 2.4% 0px;">

                </div>
         <?php endforeach; ?>


         <div class="bloco_noticia">

                 <div class="descricao_noticia">

                    <center><h2>Não contém dados nesta página!</h2></center>

                 </div>

         </div>


    </body>



</html>