<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Teste E-mail</title>
</head>
<body style="font-family: Arial, sans-serif; font-size: 14px;">
    <h3>Dados do cliente</h3>
    <div><?= $this->nome ?></div>
    <div><?= $this->email ?></div>
    <div><?= $this->cidade ?></div>
    <div><?= $this->telefone ?></div>
    <h3>Mensagem</h3>
    <p><?= $this->message ?></p>
    <p style="font-style: italic; font-size: 80%;">E-mail enviado em <?= $this->data ?> por BLZ Soluções Web</p>
</body>
</html>